### ISSUE TITLE
Bugs and feature requests for 3.0

### ISSUE THREAD

**Issue by xeeek** [Maxximou5/csgo-deathmatch#104]
After loading the plugin, all steps are turned off, even your own.
And you can not turn off random spawn, in the config it simply does not exist.

**Comment by christophlsa** [comment]
I don't have problems with the sounds. The other point I didn't test.

**Comment by xeeek** [comment]
> 
> 
> I don't have problems with the sounds. The other point I didn't test.

Do you have alpha 3.0? After disabling the plugin, the steps appear

**Comment by borzaka** [comment]
Maybe it's a feature? Deathmatches are often played without sound/with loud music, so if someone still plays it normally, the footsteps can give him an unfair advantage against the no sound players.

**Comment by xeeek** [comment]
> 
> 
> Maybe it's a feature? Deathmatches are often played without sound/with loud music, so if someone still plays it normally, the footsteps can give him an unfair advantage against the no sound players.

Probably it would be more correct to enter a variable to turn on and off in version 3.0

**Comment by MindaugasR** [comment]
About footsteps it's bug. Everything ok until I change mode, just say to HS Only. Then no steps at all, after I die, I can hear my steps again... 

Using 2.0.9

**Comment by xeeek** [comment]
Removed from the source HookSounds(); and everything was solved

**Comment by kzxt** [comment]
@Maxximou5 Any chance of FIFO weapons coming back from the 2.0.0?
