### ISSUE TITLE
(short) stuck Spawn Points on Dust2

### ISSUE THREAD

**Issue by christophlsa** [Maxximou5/csgo-deathmatch#105]
Did someone experienced also that some spawn points on dust2 result in 1s stuck at this position? Maybe it's not related to the spawn points itself but we had sometimes the problem that you couldn't move immediately.

**Comment by borzaka** [comment]
That is possible. If the ground highered, you can spawn halfway in the ground. Try to use these spawns from the develop branch:
https://github.com/Maxximou5/csgo-deathmatch/blob/development/configs/deathmatch/spawns/de_dust2.txt

There will be at least one stuck spawn at B entrance from T, but you can delete is via the editor.
