### ISSUE TITLE
[SM] Exception reported: Client 1 is not in game

### ISSUE THREAD

**Issue by x86906** [Maxximou5/csgo-deathmatch#107]
L 01/15/2020 - 22:30:48: [SM] Exception reported: Client 1 is not in game
L 01/15/2020 - 22:30:48: [SM] Blaming: deathmatch.smx
L 01/15/2020 - 22:30:48: [SM] Call stack trace:
L 01/15/2020 - 22:30:48: [SM]   [0] GetClientTeam
L 01/15/2020 - 22:30:48: [SM]   [1] Line 4, deathmatch/frames.sp::Frame_RespawnDead
L 01/16/2020 - 00:33:40: Error log file session closed.

**Comment by Maxximou5** [comment]
Thanks, I'll address this in the next update.
