### ISSUE TITLE
 Manage Step Sounds

### ISSUE THREAD

**Issue by AleksandrPe** [Maxximou5/csgo-deathmatch#108]
From time to time, on the same maps, I don’t hear the sounds of my steps and the sounds of the opponent’s steps, if I change the map to the same (repeatedly) then the sound of the steps returns. This is a big problem for me, I would like to control it.

**Comment by Maxximou5** [comment]
Which version of Deathmatch are you running?

**Comment by AleksandrPe** [comment]
Deathmatch v3.0.0 BETA

**Comment by Maxximou5** [comment]
Thanks for the report. I have been able to found out the issue, it will be fixed in the next development update.
