### ISSUE TITLE
BETA 3.0.0 - config_loader.ini syntax documentation.

### ISSUE THREAD

**Issue by codeho** [Maxximou5/csgo-deathmatch#109]
@Maxximou5

First of all, GREAT plugin. thank you so much for that. i'll be sure to donate!

and of course, i have a question 

i'm using the dev branch of the BETA with the config rotation, and i don't seem to get it work correctly.

what i want it to do:

one game runs for 60 minutes (that's all set)
then i want to rotate through different deathmatch configs for example:
1 minute of pistols.ini
then 1 minute of pistols_headshot.ini
then 1 minute of smgs.ini
then 1 minute of rifles_headshot.ini
... ect

i've tried several combinations of the config, but when i do this:
Code:
        "clients:1"                 "0:deathmatch_pistols.ini:respawn"
        "clients:1"                 "60:deathmatch_rifles.ini:respawn"
        "clients:1"                 "120:deathmatch_shotguns.ini:respawn"
        "clients:1"                 "180:deathmatch_smgs.ini:respawn"
it seems to only load the last one after 180 seconds, and ignore the other ones

when i do this:
Code:
        "clients:1"                 "0:deathmatch_pistols.ini:respawn"
        "timeleft:30"		"0:deathmatch_rifles.ini:respawn"
        "timeleft:60"              "0:deathmatch_shotguns.ini:respawn"
it only loads the first one, and never anything else (i thought maybe timeleft is time as well, but its not)

would you be so kind and explain to me how i have to set the config to do what i'd like it to do?

2nd question: whenever dm loads a new config, i'd like to display a hud message 'NOW 1 Minute Pistols, Headshot only' for example. Do you have an idea on how i could do that?

any help is greatly appreciated. Also, if you need testers for the BETA to test new stuff, i'm all for it.

-nOOgz

**Comment by Maxximou5** [comment]
> First of all, GREAT plugin. thank you so much for that. i'll be sure to donate!

Glad you think so, and thank you!
> i'm using the dev branch of the BETA with the config rotation, and i don't seem to get it work correctly.
> would you be so kind and explain to me how i have to set the config to do what i'd like it to do?

I'll probably be making it's own Github as keeping this together will be to cumbersome. Currently, how the plugin works is by getting the timeleft on the map and using that as the basis for when to activate the next config. Right now I don't have a better solution and for all purposes it works how I need it to.

So for example, if your map time is 60 minutes and at 59 minutes of a player being on that map you want to have 1 minute of shotguns, you would do: 
`"timeleft:59" 0:deathmatch_shotguns.ini:respawn"`
and after that 1 minute you wanted rifles, it would be: 
`"timeleft:58" "0:deathmatch_rifles.ini:respawn"`
Of course, if at the last 5 minutes you wanted normal deathmatch, that would be:  
`"timeleft:5" "0:deathmatch_rifles.ini:respawn"`
If at any point you wanted smgs with 20 people in the server you would do: 
`"clients:20" "0:deathmatch_pistols.ini:respawn"`
> 2nd question: whenever dm loads a new config, i'd like to display a hud message 'NOW 1 Minute Pistols, Headshot only' for example. Do you have an idea on how i could do that?

I may add something for that or a forward for other plugins to use.
> any help is greatly appreciated. Also, if you need testers for the BETA to test new stuff, i'm all for it.

By all mean, please do test it and give feedback on anything that isn't working.

**Comment by codeho** [comment]
Thanks for getting back to me so quickly.
OH, it's 'Minutes'. that i haven't tried . for some reason i thought it was seconds. thank you very much!
