### ISSUE TITLE
Client preferences on gunmenu reset after every server restart

### ISSUE THREAD

**Issue by meciarsam** [Maxximou5/csgo-deathmatch#110]
So. Im currently using 3.0.0 Beta version, but im experiencing one problem with it. Im running a MultiCFG DM server, after every server restart the client preferences on guns menu are lost. For example, player sets an AK-47, he is playing with it, but after server restart he comes back and his option is set back to random, so after every death he gets random rifle/pistol . Any solution, maybe how to store his preferences in sqlite db or something else?

**Comment by Maxximou5** [comment]
This issue was specifically addressed in the BETA release. Check to make sure that your data folder has read and write permissions, the file called _clientprefs-sqlite.sq3_, and the path should be _/csgo/addons/sourcemod/data/sqlite_.
