### ISSUE TITLE
Auto exec file for DM plugins ?

### ISSUE THREAD

**Issue by vassilidev** [Maxximou5/csgo-deathmatch#116]
Hi ! 

Ive put in my server.cfg : 
"exec dm.cfg" 
where i put all dm command to make a good dm match but ive always the warmup and the freezetime (its the gamemode_com.cfg i think but i dont want to change this file)

and last question, is it possible to set gamemode style ? like only pistol for 5 min, only HS for 5 minutes etc ? with dm_gun_menu_mode but all X second

Thx for ur beautiful plugins, i gonna give u some money i think

**Comment by Maxximou5** [comment]
If you're looking for deathmatch rotating configuration, check out the development branch -
https://github.com/Maxximou5/csgo-deathmatch/tree/development

Everything needs to be set in the deathmatch.ini file under _addons/sourcemod/configs/deathmatch_, adding variables to any other file will result in issues. v2.0.9 does not support configuration that way.

Feel free to donate, it's always appreciated.

**Comment by vassilidev** [comment]
okay thx bro for the config ?

**Comment by Maxximou5** [comment]
As for your config, you need let me know what game mode you are running, casual, competitive, etc. (e.g. game_mode 0 + game_type 0). Anything related to game variables, commands that typically start with mp_* all have to be placed into the gamemode_*_server.cfg. If they are not, they will not work, especially if they are placed in the server.cfg. Server.cfg is only executed once at server start up, gamemode_*_server.cfg is executed each time a map is changed.

* = casual, competitive, etc. (e.g. gamemode_casual_server.cfg) 
P.s. you have to create this file in your _/cfg_ folder.
