### ISSUE TITLE
3 problems

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [Maxximou5/csgo-deathmatch#12]
1. You cannot get for example: m4a1-s if you have equipped m4a1 in your inventory and same the other way around. Also with P2000 & USP. This should possible? I think other plugins made it work.

2. When you spawn, it forgets that you had a pistol before you died, so when you use "q" it switches to the knife instead. So every time you spawn you have to bring up the pistol and then the rifle for "Q" to work. Its really annoying for the players. This should also be possible, I think the older 1.5.5 plugin did not have this problem?

3. "armour" "yes" gives both helmet and armor when I only want armor (pistols only). This is not a huge problem, I fixed it by changing 1 to 0 for helmet in the .sp. But an option would be nice to have in the CFG. :)

**Comment by Maxximou5** [comment]
Fixed in v2.0.5

**Comment by BrutalCSEjziponken** [comment]
Hm. None of the fixes from this thread is in the latest patchnotes?

**Comment by Maxximou5** [comment]
Only one of those are actual bugs, which was the armor option. However several versions ago the option for full armor and just chest armor was added. The switch to secondary from primary and not knife was changed back in this update. The other being m4a1-s and m4a4 works as it has and always has, if there is an issue it would come from some other third party plugin.

**Comment by BrutalCSEjziponken** [comment]
Oh okay! So now there is only one problem left for me. The spawns. You cant have 100 spawns on each map. Thats crazy. :package: 

But I made my own so I guess this plugin is now useble again! The mainproblem was the knife/pistol thingy. :)

**Comment by Maxximou5** [comment]
Okay, you can edit line 2771 in the latest deathmatch and set it to whatever amount you need.
Let me know if it doesn't work.
