### ISSUE TITLE
New CSGO update, no damage

### ISSUE THREAD

**Issue by Safoide** [Maxximou5/csgo-deathmatch#121]
L 07/23/2020 - 21:57:45: [SM] Exception reported: Client index -1 is invalid
L 07/23/2020 - 21:57:45: [SM] Blaming: deathmatch.smx
L 07/23/2020 - 21:57:45: [SM] Call stack trace:
L 07/23/2020 - 21:57:45: [SM]   [0] GetClientWeapon
L 07/23/2020 - 21:57:45: [SM]   [1] Line 1809, deathmatch.sp::OnTraceAttack

**Comment by JayNepal-A** [comment]
Can confirm. Alongside this as well:

[SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
[SM] Blaming: deathmatch.smx
[SM] Call stack trace:
[SM]   [1] Line 1813, deathmatch.sp::OnTraceAttack

**Comment by borzaka** [comment]
I can confirm the errors,  but the game mode is till working. I can have and give damage as normal.
```
L 07/24/2020 - 12:37:29: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 07/24/2020 - 12:37:29: [SM] Blaming: deathmatch.smx
L 07/24/2020 - 12:37:29: [SM] Call stack trace:
L 07/24/2020 - 12:37:29: [SM]   [1] Line 1869, deathmatch.sp::OnTakeDamage
```

Plugin version: `"[CS:GO] Deathmatch" (2.1.0) by Maxximou5`

But the errors are keep flooding the logs.

**Comment by crashzk** [comment]
Doesn't updating SourceMod fix this problem? Have you tried?

**Comment by mauromiranda** [comment]
I have the same problem when I want to own my new deathmatch server 

Did someone solved it?

I am try 2.0.9 and 2.1.0 by Maxximou5.
I updated Sourcemod to 1.10.0.6490 and the plugin still not working.

Thanks

**Comment by borzaka** [comment]
That's not the latest SourceMod. Build 6492 contains the fix for this problem.

The latest currently is: 1.10 - build 6494
Update from the official site: https://www.sourcemod.net/downloads.php?branch=stable

**Comment by kENN1N** [comment]
> 
> 
> That's not the latest SourceMod. Build 6492 contains the fix for this problem.
> 
> The latest currently is: 1.10 - build 6494
> Update from the official site: https://www.sourcemod.net/downloads.php?branch=stable

I was having the same issue and im just to confirm that a manual update of sourcemod from their website is working like a charm.
Thanks alot!

- My GUI should update sourcemod automatically but it havent done that and i've had this issue for weeks now haha! 👍
