### ISSUE TITLE
Some spawns are holding players blocked

### ISSUE THREAD

**Issue by dwwesley** [Maxximou5/csgo-deathmatch#122]
Good afternoon, how are you ?

Dude your plugin is perfect, but some spawns are blocking players, so it is not possible to move, how to fix this bug? Or just disable that respawn?

**map mirage**
BUG respawn inside the cave
BUG respawn on the carpet in front of the mouse ladder.

**Comment by mattiascaricato** [comment]
same here

**Comment by borzaka** [comment]
Use the editor and delete the bad spawns.

Or check out the spawns in the development version:
https://github.com/Maxximou5/csgo-deathmatch/blob/development/configs/deathmatch/spawns/de_mirage.txt
