### ISSUE TITLE
Change the standard weapon

### ISSUE THREAD

**Issue by xeeek** [Maxximou5/csgo-deathmatch#124]
How can I change the standard issued weapon in 3.0 if I haven't already selected sm_guns in the menu? Now, for some reason, a random weapon is issued at the beginning, before choosing the main one

**Comment by borzaka** [comment]
Type: `!guns`
And disable random weapons.

**Comment by xeeek** [comment]
I'm talking about starting weapons when the guns menu isn't open yet
