### ISSUE TITLE
Incorrect reserve count for m4a1s

### ISSUE THREAD

**Issue by xmrv** [Maxximou5/csgo-deathmatch#131]
Reserve ammo count for m4a1s, when `dm_replenish_ammo_type 2` or `dm_replenish_ammo_type 3`, gets restored back to 40 instead of 75 after reloading. Steps to reproduce: 

- set `sv_infinite_ammo` to `0` to see the bug obviously
- set `dm_replenish_ammo_type` to `2` or `3`
- kill somebody (reserve will be 75 initially)
- reload
- reserve ammo gets restored to 40

**Comment by zahti** [comment]
It looks like this was merged to master on July 17, 2020 (patch #99), but hasn't made it into a new release. For example, you probably are using 2.0.9, but it does not have this change.
