### ISSUE TITLE
Config Loader Not Working

### ISSUE THREAD

**Issue by Shaneajm** [Maxximou5/csgo-deathmatch#144]
Hello! I'm attempting to use the `development` branch and the config loader is not actually changing the weapon configs like it should. I've attached my config_loader.ini file in case I'm just stupid 😅

Sourcemod Version: `1.10.0.6502`
Metamod Version: `1.11.0-dev+1144`
OS: `Windows`

I set the times to change every two minutes for testing purposes but even at each time in-game nothing happens.
```
"Config"
{
    "*"
    {
        "timeleft:30"               "0:deathmatch_pistols.ini:respawn"
        "timeleft:28"               "0:deathmatch_rifles.ini:respawn"
        "timeleft:26"               "0:deathmatch_smgs.ini:respawn"
        "timeleft:24"                "0:deathmatch_rifles.ini:respawn"
    }
}
```
Thanks!

**Comment by jelliesbabe** [comment]
Hey, hopefully this helps you out. You still have to declare how long you wanna run this config and you set it to 0.

SECOND: "[time](seconds):[config](filename):[option](respawn|restart|nextround)"
// I actually think its (minutes) so test a bit with it

This would create the 2 minutes of changing DMs if Im correct.

"Config"
{
    "*"
    {
        "timeleft:30"               "2:deathmatch_pistols.ini:respawn"
        "timeleft:28"               "2:deathmatch_rifles.ini:respawn"
        "timeleft:26"               "2:deathmatch_smgs.ini:respawn"
        "timeleft:24"               "2:deathmatch_rifles.ini:respawn"
    }
}
