### ISSUE TITLE
canNumber of players not working properly

### ISSUE THREAD

**Issue by Jyun5978** [Maxximou5/csgo-deathmatch#146]
The number of players in the game cannot be displayed properly. [https://imgur.com/a/3bhhn5l](url)

**Comment by h182035** [comment]
Did you figure this out? I have had the same problem and if i remember correctly it's something to do with bots on the server

**Comment by borzaka** [comment]
This is nothing to do with this plugin. It's just CS:GO dedicated server config things.

Try these:
```
// ............................. Server Query ............................. //
host_name_store 1
host_info_show 1
host_players_show 2
```

Or for me, the `host_info_show 2` worked better, but you have to try which is best for you.

More info at: https://www.gametracker.com/games/csgo/forum.php?thread=91691
