### ISSUE TITLE
Update request : Add weapon_revolver

### ISSUE THREAD

**Issue by ShoGun-KmKz** [Maxximou5/csgo-deathmatch#15]
Since 1.35.1.2 CS:GO Update, new weapon is available.

"name" : "weapon_revolver"
"defindex" : "64"
"item_class" : "weapon_deagle"
"item_type_name" : "Pistol"
"primary clip size" : "8"
"primary reserve ammo max" :	"8"

Can you add it please ?

Thx

**Comment by Maxximou5** [comment]
Will be available today in v2.0.5.
