### ISSUE TITLE
Bug? - Loss% on server

### ISSUE THREAD

**Issue by spot88** [Maxximou5/csgo-deathmatch#16]
The server is not lacking power, i only use around 30%-50% of max.  Running on a windows 7. 
E5-2640 @ 2.5Ghz 4 cores 8 threads. Running at the moment only 4 servers on it.

Check picture for the plugins list. 
![plugins-list](https://cloud.githubusercontent.com/assets/10884072/11818455/b19b9b1e-a35a-11e5-8782-295817514127.png)

Any ide what the problem can be? - server is basicly useless, only lags.

**Comment by Maxximou5** [comment]
This is not a bug nor a problem with the plugin, this has to do with you and your connection to your server. Loss deals with server side rates and the clients connection. Check that you are not on a wifi connection, that your hops are minimal to your server, and that your rates are adjusted to reflect your tickrate. If you need help, use the search function on the forums for AlliedMods and use your search engine looking for solutions to your problem.

This will now be closed.
