### ISSUE TITLE
Spawn sound at bases despite having no one spawning there

### ISSUE THREAD

**Issue by MajorErection** [Maxximou5/csgo-deathmatch#20]
I don't know if this plugin is still being supported but everyone that plays on my servers noticed that the sound of players spawning in both T and CT Base despite no one being there. The sound happens when someone spawns somewhere on the map. The sound only happens when people of the respective teams spawn. 
Eg: Terrorist spawns some where on the map the spawn sound happens in T Base.

If anyone is still supporting this plugin please reply. I am not experienced with sourcepawn but I'm looking out for a way to fix this. Until then, have a nice day everyone.

**Comment by Maxximou5** [comment]
Hello,

Yes this plugin is still being supported. My time at this point is mostly spent bug fixing, if and when there is a bug it will be fixed along with any new enhancements. Otherwise, development ceases until a bug has been reported. This sounds to be like one.

A few questions:
1. What is your **gamemode & gametype** set to?
2. Are you using the plugins spawn settings or Valve's spawn system?
3. Post your **sm version** & **sm plugins list** inside the <> code t

**Comment by MajorErection** [comment]
1. +game_type 0 +game_mode 0
2. I'm using your spawn list.
3.  `SourceMod 1.7.3-dev+5289, by AlliedModders LLC`

`"Client Preferences" (1.7.3-dev+5289) by AlliedModders LLC
 "Rock The Vote" (1.7.3-dev+5292) by AlliedModders LLC
 "Store - Trade System" (1.0) by Zephyrus
 "Admin Menu" (1.7.3-dev+5289) by AlliedModders LLC
 "Sound Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Player Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Basic Ban Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Store - The Resurrection" (1.1) by Zephyrus
 "Basic Chat" (1.7.3-dev+5289) by AlliedModders LLC
"Web Shortcuts CS:GO version" (2.3) by Franc1sco franug and James "sslice" Gray
 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
 "Anti-Flood" (1.7.3-dev+5289) by AlliedModders LLC
 "Reserved Slots" (1.7.3-dev+5289) by AlliedModders LLC
 "Basic Comm Control" (1.7.3-dev+5289) by AlliedModders LLC
 "Deathmatch" (2.0.5) by Maxximou5
 "Admin Help" (1.7.3-dev+5289) by AlliedModders LLC
 "Fun Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Basic Votes" (1.7.3-dev+5289) by AlliedModders LLC
 "Nextmap" (1.7.3-dev+5289) by AlliedModders LLC
 "AdminTag" (2.0) by KeepCalm
 "Admin File Reader" (1.7.3-dev+5289) by AlliedModders LLC
 "Basic Info Triggers" (1.7.3-dev+5289) by AlliedModders LLC
 "CS:GO Bot quota fix" (1.0) by Otstrel.ru Team
 "Updater" (1.2.2) by GoD-Tony
 "Basic Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Fun Votes" (1.7.3-dev+5289) by AlliedModders LLC
 "Server Advertisement" (2.5) by ESK0
 "MapChooser" (1.7.3-dev+5292) by AlliedModders LLC
`
