### ISSUE TITLE
Team killing loosing points

### ISSUE THREAD

**Issue by ixayldz** [Maxximou5/csgo-deathmatch#22]
i made Free for all -1  they loosing point. ?

**Comment by MajorErection** [comment]
Sincere question, why are you putting it at -1?

As far as I know, dm_free_for_all should either be 1 or 0

**Comment by Maxximou5** [comment]
@ixayldz 
I'm super confused as to what you're asking or questioning. You're going to need to explain yourself better if you want me to know what is wrong.

**Comment by ixayldz** [comment]
i am sorry i was using hlxce stats also in game when players kill teammate they loose points because of that i was think its about deatmatch but wasnt :)  Anywayi have different question how to disable sound for killings ? and awp limited ? and up pictures make default ?

**Comment by Maxximou5** [comment]
OP: The points are configured by HLXCE not by the plugin.

1). Sounds can be managed by another plugin or by the client, not this plugin.

2). To limit any weapon, change it from -1 (unlimited) to whatever you want the limit to be.

3).  No idea what "up pictures make default" means.

Closing this, as it's now off topic.
