### ISSUE TITLE
Add Team Spawn Points

### ISSUE THREAD

**Issue by ezspot** [Maxximou5/csgo-deathmatch#23]
Is there any command so we can make them our self? Was thinking about setting a AIM DM server.

**Comment by spot88** [comment]
Found the command, but is it possible to specific assign a spawn to Terror and CT.

**Comment by Maxximou5** [comment]
As of yet, no there isn't. That would require reworking all spawn points. It's not something I have time to work on yet. Though, if you wish to do a formal request, please edit your title to "Add Team Spawn Points" and edit your initial post to request it and I will be happy to add this to my list of things to do.

**Comment by spot88** [comment]
Make it possible to define where Terror and CT should spawn.
