### ISSUE TITLE
dm_gun_menu_mode 4

### ISSUE THREAD

**Issue by RED4911** [Maxximou5/csgo-deathmatch#26]
I want to make the AWP only. I fit into the config command below does not work.

mp_t_default_secondary "weapon_awp"

**Comment by greent911** [comment]
mp_t_default_primary "weapon_awp"
"secondary" is for pistol

**Comment by RED4911** [comment]
mp_t_default_primary "weapon_awp" - not work!!!

**Comment by Maxximou5** [comment]
Review this post: https://forums.alliedmods.net/showpost.php?p=2400903&postcount=244
This plugin isn't designed to be used as such, so you most edit the code and compile it yourself.

**Comment by T1MOXA** [comment]
It would be nice if the plugin supported this initially.
