### ISSUE TITLE
Gun menu: random sometimes doesn't give a weapon

### ISSUE THREAD

**Issue by melkor217** [Maxximou5/csgo-deathmatch#31]
It happens sometimes for both primary and secondary weapons with "Random" and "Random every round"

**Comment by Maxximou5** [comment]
This is fixed in v2.1.0 in the [Development Branch](https://github.com/Maxximou5/csgo-deathmatch/tree/development)

**Comment by melkor217** [comment]
Whoops, sounds for scope and fire mode switch are missing in a dev branch.
