### ISSUE TITLE
Spawnpoint editor for workshopmaps

### ISSUE THREAD

**Issue by shnytzl** [Maxximou5/csgo-deathmatch#34]
Hi,
I am trying to add spawnpoints for a workshop map (i.e. the maps are located in maps/workshop and updated via the official workshop) . After I added my desired spawns I disable edit mode and press "save configuration". Unfortunately this is when "[DM] Configuration could not be saved." pops up in chat. What do I have to do for it to save the config? I have tried both 2.0.5 and 2.1.0, latest Sourcmod/Metamod

**Comment by Dreizehnt** [comment]
Hello. Maxximou5, perhaps you will be able to understand if look as it is implemented here?
[SpawnTools7 CS:GO](https://forums.alliedmods.net/showpost.php?p=2399733&postcount=6)
And the plug-in is supported?))

**Comment by Maxximou5** [comment]
@Dreizehnt Thank you for the input and reference, I'll be sure to check it out.

**Comment by Maxximou5** [comment]
Will be released in the next version.
