### ISSUE TITLE
de_cbble B stairs spawn stuck 

### ISSUE THREAD

**Issue by faarecsgo** [Maxximou5/csgo-deathmatch#37]
There is a spawn bug that causes the players to be stuck on de_cbble B stairs (the spawn location at the bottom of them, not the middle one).

Here is a .txt without the spawn location. I didn't change it, I removed it. I might add it back later but there are already 60+ spawn locations so that should do the trick.

File location : /addons/sourcemod/configs/deathmatch/spawns 
[de_cbble.txt](https://github.com/Maxximou5/csgo-deathmatch/files/445513/de_cbble.txt)

**Comment by Maxximou5** [comment]
Was corrected in v2.0.6 and on.
