### ISSUE TITLE
P2000 BUG

### ISSUE THREAD

**Issue by BENCSGO** [Maxximou5/csgo-deathmatch#39]
**Install the plugin on my server, the gun weapon p2000 has error like and sounds and removes damage as the desert gun deagle**

**Comment by MajorErection** [comment]
Which version have you installed? Make sure that it's v2.0.7.
Also, you need to equip p2000 in your loadout for it to work properly in the server. As stated by Maxximou5, any other ways to 'fix' this problem will result in a gslt ban.

**Comment by BENCSGO** [comment]
Hi @MajorErection , i installed v2.0.7 and p2000 presents the error, I let my server ip 76.74.199.150:27015

**Comment by MajorErection** [comment]
I went to your server and see this "[CS:GO] Deathmatch" (2.0.6) by Maxximou5

You need to update your plugin. If you already have, please use 'sm plugins reload deathmatch' in your server console to refresh the plugin. Alternatively you can just change the map.
