### ISSUE TITLE
New de_inferno map

### ISSUE THREAD

**Issue by Luckiris** [Maxximou5/csgo-deathmatch#40]
I have a problem on the new de_inferno map. 

Some spawns are broken ( for exemple, i spawn outside of the map sometimes ), how can I fix this ?

Thanks in advance.

**Comment by morpig** [comment]
remove all the spawnpoint config, and create them from scratch. i forgot the command, but there's a command for spawnpoints

**Comment by Luckiris** [comment]
Thanks for the reply.

I will look into this for the command.

**Comment by Luckiris** [comment]
I found the command. 

Thanks for the help !
