### ISSUE TITLE
Unable to kill except in HSMOD

### ISSUE THREAD

**Issue by tiibzbe** [Maxximou5/csgo-deathmatch#41]
Hi, just install the plugin on 3 differents servers, same config (1 HSMOD FFA / 1 Only Pistol FFA / 1 FFA) i can make frags on the HSMOD but on the other two servs (only pistol & ffa) i can't.. 

I really don't know what happened but it's looks like every players are in godmode

Tested:

After activate HSMOD on a serv where i can't kill a player -> Serv works, I can kill with a headshoot. When I switch off HSMOD, i can't kill players again ..

SourceMod v1.8.0
MetaMod v1.10.7

**Comment by BatMen** [comment]
Same here. Don't know why...

**Comment by BatMen** [comment]
It seems that tha **noKnifeDamage* feature does not work. 
Every weapon deals 0 damage if option dm_no_knife_damage activated.

**Comment by Maxximou5** [comment]
I've been able to resolve the issues with using **dm_no_knife_damage**. Additionally, this also will fix any problems with **dm_headshot_only** and **dm_headshot_only_allow_knife**.

It will be fixed in the next version update.

**Comment by Maxximou5** [comment]
Fixed!
https://github.com/Maxximou5/csgo-deathmatch/commit/62bdad9508930b99a2f39878df115a4bf5c5da5c
