### ISSUE TITLE
"mp_timelimit" is invalidated

### ISSUE THREAD

**Issue by EwDirt** [Maxximou5/csgo-deathmatch#44]
When using the plugin, my server experiences a countdown to "0:00" and will continue indefinitely.

**Comment by MajorErection** [comment]
I believe the cvar mp_ignore_round_win_conditions is set to 1. Change this to 0 and it should work fine.

**Comment by EwDirt** [comment]
Just tried a round with the command, it appeared to be 0 by default, but I made sure it was 0. Sadly no change/effect http://i.imgur.com/QAaSTT9.png

**Comment by Maxximou5** [comment]
Gamemode & Gametype?
