### ISSUE TITLE
Remove vulnerability.

### ISSUE THREAD

**Issue by Sevrik** [Maxximou5/csgo-deathmatch#45]
Hello, thanks for the great plugin.

Please tell me how to remove the vulnerability?
I was looking in the settings, so I found none. :(

Thank you very much for your answer.
Sorry for my English translator.

**Comment by Sevrik** [comment]
say, please, this team is responsible for the vulnerability?

**Comment by Maxximou5** [comment]
This is for issues with the plugin, not with personal server help.
Go to the thread for that: https://forums.alliedmods.net/showthread.php?t=246405

If you don't want spawn protection, set it to "0.0" if you do, leave it at "1.0" or higher.
