### ISSUE TITLE
Round Problem

### ISSUE THREAD

**Issue by GreYzZ** [Maxximou5/csgo-deathmatch#46]
Hello,
I got a little problem with the rounds. So I set it to classic casual and as default there are 15 rounds.
But I want that the game is like 20 Minutes 1 round and then mapchange.

Is that possible? Hope you can help me

**Comment by Froster2406** [comment]
If you have set your server to classic casual, you will have to edit your gamemode_casual.cfg file on your server. It should be located somwhere around "/YOURSERVERNAME/serverfiles/csgo/cfg". 
Change the entrys on the following variables inside the file:
**mp_timelimit	        30
mp_maxrounds	1**

optional:
**mp_warmuptime	1**

Hope i could help you
Froster
