### ISSUE TITLE
Clip restored on pre-reload finish.

### ISSUE THREAD

**Issue by Bobakanoosh** [Maxximou5/csgo-deathmatch#50]
Ammo is restored instantly after a player starts a reload, so all you have to do is start the reload and then switch weapons and switch back. Is this intentional?

**Comment by Maxximou5** [comment]
Yes. If you have it set so ammo is replenish on reload ("dm_replenish_ammo", "1", "Replenish ammo on reload."), the ammo will be replenished when you initiate reloading.

**Comment by Maxximou5** [comment]
Note: This has been done away with, instead a clip is refilled when the gun is empty.
