### ISSUE TITLE
Undefined symbol "attackerAP"

### ISSUE THREAD

**Issue by RED4911** [Maxximou5/csgo-deathmatch#54]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// deathmatch.sp
//
// C:\Users\Desktop\sourcemod\scripting\deathmatch.sp(1593) :
 error 017: undefined symbol "attackerAP"
//
// 1 Error.
//
// Compilation Time: 0,92 sec
// ----------------------------------------

Press enter to exit ...

**Comment by Maxximou5** [comment]
The releases will always compile: https://github.com/Maxximou5/csgo-deathmatch/releases
Don't expect the repository to always compile.
