### ISSUE TITLE
Pistol Only Mode not working properly

### ISSUE THREAD

**Issue by maefju** [Maxximou5/csgo-deathmatch#57]
Hello,

when i set dm_gun_menu_mode 3 the gun menu is properly showing only pistols. When i initally spawn in the game i only can select pistols as intended. But when i then type "guns" into chat and select another pistol. The next time i respawn i've got an ak47 in my hands. Is there any setting i missed or is this a bug?

My dm config:

dm_welcomemsg "Welcome to Deathmatch, have fun!"
dm_enabled 1 // Enable deathmatch.
dm_valve_deathmatch 0 //  Enable compatibility for Valves Deathmatch (game_type 1 & game_mode 2) or Custom (game_type 3 & game_mode 0).
dm_welcomemsg 1 // Display a message saying that your server is running Deathmatch.
dm_free_for_all 1 // Free for all mode.
dm_hide_radar 1 // Hides the radar from players.
dm_display_panel 0 // Display a panel showing health of the victim.
dm_display_panel_damage 0 // Display a panel showing damage done to a player.
dm_sounds_bodyshots 1 // Enable the sounds of bodyshots.
dm_sounds_headshots 1 // Enable the sounds of headshots.
dm_headshot_only 1 // Headshot Only mode.
dm_headshot_only_allow_world 0 //- Enable world damage during headshot only mode.
dm_headshot_only_allow_knife 0 // Enable knife damage during headshot only mode.
dm_headshot_only_allow_taser 0 // Enable taser damage during headshot only mode.
dm_headshot_only_allow_nade 0 // Enable grenade damage during headshot only mode.
dm_remove_objectives  1 // Disables bomb sites, and removes c4 and hostages.
dm_respawning 1 // Enable respawning.
dm_respawn_time 1.0 // Respawn time.
dm_gun_menu_mode 3 // 1) Enabled. 2) Primary weapons only. 3) Secondary weapons only. 4) Random weapons only. 5) Disabled.
dm_los_spawning 1 // Enable line of sight spawning.
dm_los_attempts 10 //  Maximum attempts to find a suitable line of sight spawn point.
dm_spawn_distance 0 // Minimum distance from enemies at which a player can spawn.
dm_sp_time  0.6 // Spawn protection time.
dm_no_knife_damage 0 // Knives do NO damage to players.
dm_remove_weapons  1 // Remove ground weapons.
dm_replenish_ammo 1 // Replenish ammo on reload.
dm_replenish_clip 1 //Replenish ammo clip on kill.
dm_replenish_reserve 1 // Replenish ammo reserve on kill.
dm_replenish_grenade 0 // Unlimited player grenades.
dm_replenish_hegrenade 0 // Unlimited hegrenades.
dm_replenish_grenade_kill 0  // Give players their grenade back on successful kill.
dm_hp_start 100 // Spawn HP.
dm_hp_max 100 // Maximum HP.
dm_hp_kill 5  // HP per kill.
dm_hp_hs 10 // HP per headshot kill.
dm_hp_knife 50 // HP per knife kill.
dm_hp_messages 1 // Display HP messages.
dm_ap_max 100 // Maximum Armor Points (AP).
dm_ap_kill 5 // Armor Points (AP) per kill.
dm_ap_hs 10 // Armor Points (AP) per headshot kill.
dm_ap_knife 50 // Armor Points (AP) per knife kill.
dm_ap_nade 30 // Armor Points (AP) per nade kill.
dm_ap_messages 1 // messaDisplay AP messages.
dm_nade_messages 1 //- Display grenade messages.
dm_armor 1 // Give players chest armor.
dm_armor_full 0 // Give players full armor.
dm_zeus 0 //Give players a taser.
dm_nades_incendiary 0 // Number of incendiary grenades to give each player.
dm_nades_molotov 0 // Number of molotov grenades to give each player.
dm_nades_decoy 0 // Number of decoy grenades to give each player.
dm_nades_flashbang 0 //Number of flashbang grenades to give each player.
dm_nades_he 0 // Number of HE grenades to give each player.
dm_hp_nade 30 // HP per nade kill.
dm_nades_smoke 0 // Number of smoke grenades to give each player.

say "PISTOLS - ONLY HEADSHOTS"
say "PISTOLS - ONLY HEADSHOTS"
say "PISTOLS - ONLY HEADSHOTS"

Greetings.

**Comment by tumenor** [comment]
I also have this issue.

**Comment by Maxximou5** [comment]
This has been resolved in v2.0.8
