### ISSUE TITLE
Autoswitch gamemode

### ISSUE THREAD

**Issue by Asepsis** [Maxximou5/csgo-deathmatch#58]
Hey their,
first I wanna thank you for this plugin :) I really like it. I have a request, is there a way that the gamemode auto switchs between hs only (no matter what weapon), pistole only and rifle only, maybe every 5 minutes a switch, and after 3 switchs map change?

greetings

**Comment by Maxximou5** [comment]
This would be outside the realm of this plugin. You should make a request here: [ALLIEDMODS](https://forums.alliedmods.net/forumdisplay.php?f=60)
