### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RED4911** [Maxximou5/csgo-deathmatch#69]
L 12/31/2017 - 22:04:57: [SM] Exception reported: Array index is out of bounds
L 12/31/2017 - 22:04:57: [SM] Blaming: deathmatch.smx
L 12/31/2017 - 22:04:57: [SM] Call stack trace:
L 12/31/2017 - 22:04:57: [SM] [1] Line 1279, C:\sourcemod\scripting\deathmatch.sp::Event_Say

**Comment by Maxximou5** [comment]
This has been corrected in v2.0.8
