### ISSUE TITLE
[SUGGESTED] Privileges for Administrators

### ISSUE THREAD

**Issue by paulocrash** [Maxximou5/csgo-deathmatch#76]
I could put privileges option for administrators in the plugin, for example:
```
Default:
dm_hp_max - (Default) 100 - Maximum HP.
For administrators:
dm_hp_max - (Default) 150- Maximum HP.
```
```
Default:
dm_hp_kill - (Default) 5 - HP per kill.
For administrators:
dm_hp_kill - (Default) 5 - HP per kill.
```
Put more money for administrators, more vest, teaser only for administrators.

Among other options, would it be possible?

**Comment by Maxximou5** [comment]
Yes, it's possible; however, I do not plan on adding it to this plugin. Modifications for admin only options you want done will need to be paid for or be done by another developer. This plugin is not intended for admin only perks. Additionally, you may also request a plugin that adds extra HP or AP to an admin when they get a kill, you can do so from here: [ALLIEDMODS](https://forums.alliedmods.net/forumdisplay.php?f=60).
