### ISSUE TITLE
dm_spawn_time wrong identifier on main page

### ISSUE THREAD

**Issue by Xatenev** [Maxximou5/csgo-deathmatch#79]
Hi,

[on the main page] the convar dm_spawn_time is wrongfully named dm_sp_time.

> dm_sp_time - (Default) 1.0 - Spawn protection time.

As we can see [in the source] the convar is called dm_spawn_time.

[on the main page]: https://github.com/Maxximou5/csgo-deathmatch#convars
[in the source]: https://github.com/Maxximou5/csgo-deathmatch/blob/a64bd33c4912d92ed3a590749b23cea27de04560/scripting/deathmatch.sp#L757

I've created a pull request for this: #80

**Comment by Maxximou5** [comment]
Thank you.
