### ISSUE TITLE
ERROR: [SM] Exception reported: Array index out-of-bounds

### ISSUE THREAD

**Issue by fkMain** [Maxximou5/csgo-deathmatch#84]
L 07/16/2018 - 17:45:47: [SM] Exception reported: Array index out-of-bounds (index 325, limit 66)
L 07/16/2018 - 17:45:47: [SM] Blaming: deathmatch.smx
L 07/16/2018 - 17:45:47: [SM] Call stack trace:
L 07/16/2018 - 17:45:47: [SM]   [1] Line 1853, C:\Users\light\Desktop\scripting 1.9\deathmatch.sp::OnTakeDamage
L 07/16/2018 - 17:45:57: [SM] Exception reported: Array index out-of-bounds (index 296, limit 66)

 SourceMod (1.9.0.6245)

**Comment by borzaka** [comment]
I have the same issue. This is filling my SourceMod error logs entirely.
This continues forever (until the map ends) in every second:

```
L 09/17/2019 - 21:03:53: [SM] Exception reported: Array index out-of-bounds (index 774, limit 66)
L 09/17/2019 - 21:03:53: [SM] Blaming: deathmatch.smx
L 09/17/2019 - 21:03:53: [SM] Call stack trace:
L 09/17/2019 - 21:03:53: [SM]   [1] Line 1869, deathmatch.sp::OnTakeDamage
```

Any suggestion to avoid this?
