### ISSUE TITLE
Please add menu pick gun in language translation

### ISSUE THREAD

**Issue by panikajo** [Maxximou5/csgo-deathmatch#87]
Hi can you add please.
Weapon Menu in translation?
i want translate this to Russian.
    menu.AddItem("New", "New weapons");
    menu.AddItem("Same", "Same weapons", allowSameWeapons);
    menu.AddItem("Random", "Random weapons");

**Comment by Maxximou5** [comment]
If you would like the translations for:

- New weapons
- Same weapons
- Random weapons

Please provide the translation(s) for them.

**Comment by panikajo** [comment]
1. Новое оружие
2. Предыдущее оружие
3. Рандомное оружие

(Russian language)
